endpoint: 'https://s3.mpi-bn.mpg.de'
username: '' #set credentials skript try to find buckets as public ones and with the credetials
accesskey: '' #secret for S3
buckets: #buckets to download
  data-foottrack-2020: ['*'] #list of patters for file filtering example: '*.txt',  'folder/*.bw'